[package]
name = "rson"
version = "0.1.0"
authors = ["masa-suzu <11026517+masa-suzu@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.37"